### PR TITLE
Resolve bash executable path through the PATH variable

### PR DESCRIPTION
**Pull request by yurivict**

### CODE REVIEW

**Comment by eisenhauer** [comment]
I'm less clear on the need for this.  As far as I know /bin/bash exists most everywhere (and certainly on the systems where the ci scripts are run.  Is there somewhere that /bin/bash is unavailable which causes problems in dill-config?

**Comment by yurivict** [comment]
> As far as I know /bin/bash exists most everywhere ...

No.

On FreeBSD and all *BSDs bash is in /usr/local/bin/bash.

bash in general can be installed anywhere, but is usually installed in /bin/bash.

**Comment by yurivict** [comment]
bash is not a part of the operating system.

bash is one of shells. It is just another package that is usually installed by users. There are other shells as well.

**Comment by eisenhauer** [comment]
Yeah, I did BSD 4.2 on a VAX back in the day, but of course that was before bash.   I'm happy to accept the change to dill-config.in, since that will run in a target environment, but I'll keep the direct reference to /bin/bash in the CI platforms until such a time as we're running CI on a platform that needs the change.

**Comment by yurivict** [comment]
Ok.
I'd close this then since this isn't critical.

**Pull request closed without merging**
